### PR TITLE
Append Multi-Arch: foreign to config-package-dev

### PR DESCRIPTION
**Pull request by mrksngl**
Enables you to build packages depending on config-package-dev for foreign architectures.

### CODE REVIEW

**Comment by geofft** [comment]
Aha, apparently this is needed for `apt-get build-dep -a` to work:

```
(unstable-amd64-sbuild)root@titan:~# cat /etc/apt/sources.list.d/debathena.list
deb https://debathena.mit.edu/apt stretch debathena-config
deb-src https://debathena.mit.edu/apt stretch debathena-config
(unstable-amd64-sbuild)root@titan:~# apt-get build-dep -a i386 debathena-bash-config
[...]
 builddeps:debathena-shell-config:i386 : Depends: config-package-dev:i386 (>= 5.0~) but it is not installable
```

Adding M-A: foreign fixes it. I'll merge this for 5.5, but now I'm also wondering if packages _using_ config-package-dev should do the same (and therefore whether we should update the examples and documentation too). Probably it only matters if config packages are used as build-depends?

(Also I'm surprised that `apt-get build-dep -a` and `dpkg-checkbuilddeps -a` behave differently)

**Comment by mrksngl** [comment]
Yes, this is essentially what we were trying to do. We have a source package (let's name it S) build-depending on config-package-dev. S is to be cross-built for the armhf architecture.

I suspect that packages using config-package-dev should include M-A: foreign, as this would allow apt-get build-dep to assume that a package for a foreign architecture can be used for build-dependencies, which is not necessarily true.
So far I've only seen adding "M-A: foreign" to "Architecture: all" packages in order to solve our above problem, as hinted by https://wiki.debian.org/MultiArch/Hints#set_Multi-Arch:_foreign

I'm also surprised that apt-get build-dep and dpkg-checkbuilddeps behave differently ;)

**Comment by geofft** [comment]
OK, from reading that hint page and the [spec](https://wiki.ubuntu.com/MultiarchSpec) and asking on #multiarch, it sounds like `Architecture: all` without `Multi-Arch: foreign` is rarely correct: it's only needed when the package has some reason that it must only be considered as installed for the native architecture, e.g., maintainer scripts do something architecture-dependent (like compiling files) or it has a non-multiarch dependency _and_ it re-exports that package's interface in an architecture-relevant way (it makes a symlink to a shared library or something&mdash;if it just calls a binary from the dependency as a subprocess, it doesn't matter what architecture the binary is).  And it seems to me like these use cases are better solved by just making the package `Arch: any` (have the maintainer scripts write to arch-specific directories, or if all the dependencies of your metapackage are multiarch and the dependency is arch-relevant, make your metapackage `Arch: any` + `M-A: foreign` so you can have multiple arches of it and its deps installed). So `Arch: all` + `M-A: no` (or unset) is basically only useful if the package itself is not multiarch-compatible or one of its dependencies is.

Also it sounds like that not setting `M-A: foreign` unnecessarily complicates changing architectures. If I have an i386 machine I'm switching in-place to amd64, and I have `debathena-firefox-config` (all) installed which depends on `firefox` (i386), switching architectures to amd64 will cause `debathena-firefox-config` to be broken until I install `firefox:amd64`, which isn't actually something that `debathena-firefox-config` needs me to do yet.

So I'm also adding `Multi-Arch: foreign` to the examples in the package, and I'll update the example on our website, too. I'll upload 5.5 (#3) tomorrow night unless I forget.

Thanks for making me look into this, I understand multiarch better now!

**Comment by mrksngl** [comment]
Ah ok. I didn't have a look in the examples, so I didn't know they were Arch: all. If I did, I might have given another answer - I was having our use case in mind (Arch: any), where M-A: foreign would be an error.
Sorry if I confused you, but it seems now you know the rules better than me ;)

**Comment by geofft** [comment]
config-package-dev 5.5 is now in Debian unstable with this patch. If you need a Debian backport let me know (I can do that myself; I can also request an Ubuntu backport but it's probably faster for you to backport it locally).

**Comment by mrksngl** [comment]
Any chance that it will appear in testing soon? Official backports are (as far as I understood) not meant for sid packages to be ported to any other distribution. Our current solution is to have the package in our own repository which we need anyway, but we don't really like that solution.

**Comment by geofft** [comment]
It should migrate automatically from unstable to testing 5 days after upload, so, Saturday night.

**Comment by mrksngl** [comment]
Good to know, thanks ;)

**Pull request merged**
